batch_size: 64
bidirectional: false
ckpt: ../ckpt/pld_74/200131.pth
crepe: full
experiment_name: DDSP_pld_74
f0_threshold: 0.5
frame_resolution: 0.004
gpu: 0
gru_units: 512
loss: mss
lr: 0.001
lr_decay: 0.98
lr_min: 1.0e-07
lr_scheduler: multi
metric: mss
mlp_layers: 3
mlp_units: 512
n_fft: 2048
n_freq: 65
n_harmonics: 101
n_mels: 128
n_mfcc: 30
num_step: 100000
num_workers: 0 # > 0 Does not work on local Mac
optimizer: radam
resume: false
sample_rate: 16000
seed: 940513
tensorboard_dir: ../tensorboard_log/
# HACK: for now, train=test
test: /Users/piyush/datasets/PouringLiquidsData/resized_clips_wav_16k_cleaned/
train: /Users/piyush/datasets/PouringLiquidsData/resized_clips_wav_16k_cleaned/
use_reverb: true
use_z: false
# valid_waveform_sec: 12
valid_waveform_sec: 1
validation_interval: 1000
waveform_sec: 1
z_units: 16
